seed = 0
batch_size = 256
patience = 16
n_epochs = 10
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/adult"
num_policy = "noisy-quantile"
cat_policy = "ordinal"

[optimizer]
type = "AdamW"
lr = 0.00010632258766605092
weight_decay = 0.07951092079903721

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 4
d_block = 400
dropout = 0.23115082929957356
