seed = 0
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/house"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.0003938123210569871
weight_decay = 0.0380079611703752

[model]
arch_type = "plain"

[model.backbone]
type = "MLP"
n_blocks = 2
d_block = 800
dropout = 0.43046828580105934

[model.num_embeddings]
type = "PeriodicEmbeddings"
n_frequencies = 28
d_embedding = 24
frequency_init_scale = 0.011960694327801545
lite = false
